server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pre_project
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
    show-sql: true
  main:
    web-application-type: servlet